sonar.projectKey=mundial-2026-simulator
sonar.projectName=Mundial 2026 - Simulator API

sonar.organization=dhdgcmfdm140601-hub
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,venv/**,allure-report/**,allure-results/**,docs/**,static/**,**/*.md

sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml
